name: "playstation-box"
description: "Update a pinned gist to contain PlayStation stats"
branding:
  icon: "flag"
  color: "yellow"
runs:
  using: 'composite'
  steps:
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Install Dependencies
      shell: bash
      run: pip install -r requirements.txt
    - name: Run
      shell: bash
      run: python src/main.py
